import type { Metadata } from "next";
import MainLayout from "./layout/main-layout";

export const metadata: Metadata = {
  title: "First App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body>
        <div>
        <MainLayout>
          {children}
        </MainLayout>
        </div>
      </body>
    </html>
  );
}
